apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nginxes.nginx.operator.t.io
spec:
  group: nginx.operator.t.io
  version: v1
  names:
    kind: Nginx
    listKind: NginxList
    plural: nginxes
    singular: nginx
  scope: Namespaced
  subresources:
    status: {}
